name=cockpit Library
version=1.0.0
author=Fredrik Hoffman
maintainer=Fredrik Hoffman mail@fredrikhoffman.se
sentence=Common code for Arduion of the Cockpit project
paragraph=Common code for Arduion of the Cockpit project
category=Other
url=https://github.com/stfrha/cockpit_arduino_library
architectures=*
includes=cockpit.h

